export const GET_DATA_POINTS_FAILURE = "@@map/GET_DATA_POINTS_FAILURE";
export const GET_DATA_POINTS_PENDING = "@@map/GET_DATA_POINTS_PENDING";
export const GET_DATA_POINTS_SUCCESS = "@@map/GET_DATA_POINTS_SUCCESS";
