export const SET_COORDINATES = "@@user/SET_COORDINATES";
export const STORE_ID_FAILURE = "@@user/STORE_ID_FAILURE";
export const STORE_ID_SUCCESS = "@@user/STORE_ID_SUCCESS";
export const SUBMIT_SYMPTOMS_FAILURE = "@@user/SUBMIT_SYMPTOMS_FAILURE";
export const SUBMIT_SYMPTOMS_PENDING = "@@user/SUBMIT_SYMPTOMS_PENDING";
export const SUBMIT_SYMPTOMS_SUCCESS = "@@user/SUBMIT_SYMPTOMS_SUCCESS";
