export const SET_COORDINATES = "@@user/SET_COORDINATES";
export const SET_LOCALE = "@@user/SET_LOCALE";
export const STORE_FINGERPRINT_FAILURE = "@@user/STORE_FINGERPRINT_FAILURE";
export const STORE_FINGERPRINT_SUCCESS = "@@user/STORE_FINGERPRINT_SUCCESS";
export const SUBMIT_SYMPTOMS_FAILURE = "@@user/SUBMIT_SYMPTOMS_FAILURE";
export const SUBMIT_SYMPTOMS_PENDING = "@@user/SUBMIT_SYMPTOMS_PENDING";
export const SUBMIT_SYMPTOMS_SUCCESS = "@@user/SUBMIT_SYMPTOMS_SUCCESS";
